### PR TITLE
Created Bank Customer Churn Prediction

### PR DESCRIPTION
**Pull request by NIKITA320495**
# Pull Request for ML-Crate 💡

## Issue Title: 

- **Info about the related issue (Aim of the project)** :  Create bank customer churn prediction with web app
- **Name:** Nikita
- **GitHub ID:** https://github.com/NIKITA320495
- **Idenitfy yourself:** Contributor

Closes: #609 

### Describe the add-ons or changes you've made 📃
created a bank customer churn prediction using different machine learning algorithms and integrated it with streamlit to make a webapp

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by NIKITA320495** [comment]
@abhisheks008 created the project , kindly review it and do let me know for any changes (if any)

**Comment by abhisheks008** [comment]
There are 1606 files showing in the log! Please remove the not so required files and update the structure of the project.

**Comment by NIKITA320495** [comment]
@abhisheks008 i have done the required changes how should i proceed further like do i have to create another PR?

**Comment by abhisheks008** [comment]
> @abhisheks008 kindly update please

Hi @NIKITA320495 sorry for the delay.

Need these changes,
1. Update the file name as `README.md`.
2. In the Web App folder please put a demonstration video of the working of the web app. Also add a README.md file inside the Web App folder and follow the template, https://github.com/abhisheks008/ML-Crate/blob/main/.github/web-app-readme-template.md

**Comment by NIKITA320495** [comment]
@abhisheks008 done!!!

**Comment by abhisheks008** [comment]
Hi @NIKITA320495 please share your email address for further communications.

**Comment by NIKITA320495** [comment]
@abhisheks008  here it is!!
nikitababb036@gmail.com

**Pull request merged**
