### PR TITLE
Federal grants and opportunities Analysis

### PR DESCRIPTION
**Pull request by adi271001**
# Pull Request for ML-Crate 💡

## Issue Title:  #516  federal grats and opportunities analysis 

- **Info about the related issue (Aim of the project)** :  to analyze and clasiify federal grants and opportunities dataset also using regression to find patterns in data
- **Name:**  Aditya D
- **GitHub ID:**  adi271001
- **Idenitfy yourself:**  JWOC Participant

Closes: #issue number that will be closed through this PR #516

### Describe the add-ons or changes you've made 📃

added project folder as per rulesq

Give a clear description of what have you added or modifications made
project folders , dataset , model , images , result files

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
By dividing data into train and test
Describe how have you verified the changes made
graphs showcasing no under or over fitting of data

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Update the folder name as Federal Grants and Funding Opportunities Analysis, no hyphen and no underscore.
Put conclusion in the README file.
@adi271001

**Comment by adi271001** [comment]
@abhisheks008 done

**Comment by abhisheks008** [comment]
image

Not showing the image.

**Comment by adi271001** [comment]
@abhisheks008 fixed it

**Review by abhisheks008 — APPROVED** [review]
Approved @adi271001

**Comment by abhisheks008** [comment]
Please share your email ID for further communication @adi271001

**Comment by adi271001** [comment]
@abhisheks008 my email id is ibetanibex@gmail.com

**Pull request merged**
