### PR TITLE
Concrete Strength Calculation

### PR DESCRIPTION
**Pull request by sankalp-srivastava**
## Issue Title : Concrete Strength Calculation

- Info about the related issue (Aim of the project)
-  Calculate the strength of the concrete using Machine Learning techniques.

- [x] SWOC Participant 
- [ ] JWOC Participant
- [ ] Contributor

- **Name:** Sankalp Srivastava
- **GitHub ID:** github.com/sankalp-srivastava

(Mention these details are must)

Closes: #96 

### Describe the add-ons or changes you've made

done eda and created 5 models and made predicitons. Also done parameter tuning of xgboost.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by sankalp-srivastava** [comment]
@abhisheks008 Now the problem is fixed. Had to reset back and commit again

**Comment by abhisheks008** [comment]
`Dataset` folder is missing buddy @sankalp-srivastava

**Comment by sankalp-srivastava** [comment]
Th folder is now added. I think I missed to add the folder in git tracking

**Comment by abhisheks008** [comment]
LGTM! Your PR is merged and approved @sankalp-srivastava

**Pull request merged**
