### PR TITLE
Online Course Engagement

### PR DESCRIPTION
**Pull request by siddhant4ds**
# Pull Request for ML-Crate 💡

## Issue Title:  Online Course Engagement

- **Info about the related issue (Aim of the project)** :  Predicting online course completion status based on user demographics and course-specific engagement metrics.
- **Name:**  Siddhant Tiwari
- **Email ID for further communication**:  siddhant.tiwari.ds@gmail.com
- **GitHub ID:**  siddhant4ds
- **Identify yourself:**  SSOC-3 Contributor

Closes: #696 

### Describe the add-ons or changes you've made 📃

1. Exploratory analysis of features: cleaning, preprocessing and data visualization.
2. Feature engineering: discretizing numerical features.
3. Feature selection: statistical tests, model-based feature importances.
4. Created a holdout set for testing all the models using Stratified sampling to maintain imbalance ratio.
5. Training a simple linear model as baseline, using a standard modeling framework to be used for other models.
6. Training and validation using different feature sets: discriminant analysis, naive bayes, K-nearest neighbours, tree models, tree ensembles, gradient-boosting trees and neural networks.
7. Models were tuned and evaluated based on accuracy score and ROC-AUC score, since the target classes are fairly balanced.
8. Created a Streamlit web app to provide an interface for testing new data points with appropriate input methods. For inference, the best model is chosen.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Reproducibility: All experiments run with fixed random seed. Multiple runs of each notebook to produce same results. 

Dependencies: Code run on local setup as well as cloud-hosted notebooks (Kaggle).

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
It will be better if you combine all the models in a single Jupyter Notebook.

**Comment by siddhant4ds** [comment]
> It will be better if you combine all the models in a single Jupyter Notebook.

Sure, I can do that. I had just separated them based on model complexity.

**Comment by siddhant4ds** [comment]
@abhisheks008 I have made the requested changes. Let me know if an further changes are required. Thanks.

**Review by abhisheks008 — APPROVED** [review]
Approved ✅ @siddhant4ds

**Pull request merged**
