### PR TITLE
ACI IoT Network Traffic Dataset Analysis

### PR DESCRIPTION
**Pull request by why-aditi**
# Pull Request for ML-Crate 💡

## Issue Title: ACI IoT Network Traffic Dataset Analysis

- **Info about the related issue (Aim of the project)** : Analyze the traffic dataset
- **Name:** Aditi Kala
- **Email ID for further communication**: aditi25.kala@gmail.com
- **GitHub ID:** https://github.com/why-aditi
- **Idenitfy yourself:** SSOC'24

Closes: #502 

### Describe the add-ons or changes you've made 📃

I've implemented 3 models after performing EDA and preprocessing the data

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Tested on 20% of the dataset

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Remove the `.idea` folder.

**Comment by abhisheks008** [comment]
Need to implement at least 6-7 models for getting the Intermediate tag else this will be considered as Beginner tag.

**Comment by why-aditi** [comment]
> Need to implement at least 6-7 models for getting the Intermediate tag else this will be considered as Beginner tag.

I'll implement more models

**Comment by why-aditi** [comment]
> Need to implement at least 6-7 models for getting the Intermediate tag else this will be considered as Beginner tag.

I've implemented 6 Models and updated the readme as well. Kindly check

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved @why-aditi

**Pull request merged**
