### PR TITLE
Mineral classification

### PR DESCRIPTION
**Pull request by tanuj437**
# Pull Request for ML-Crate 💡

## Issue Title: Mineral Classification

- **Info about the related issue (Aim of the project)** : To Classify the mineral photo 
- **Name:** Tanuj Saxena
- **Email ID for further communication**: tanuj.saxena.rks@gmail.com
- **GitHub ID:** tanuj437
- **Idenitfy yourself:** SSOC'24 Contributor

Closes: #467  number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

I've included a full README.md file in the mineral classification project's folder. This README.md file contains thorough descriptions and visual representations of numerous analyses and model outputs for the mineral classification problem. It contains explanations and graphics for label distribution methods such as count distribution, and model performance outputs (SVM, Random Forest, K-NN, CNN, Logistic Regression, Decision Tree Classification, Extra Tree Classification). These additions are intended to improve the clarity and understanding of the project's visual and analytical components.

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️
I have tested it on webapp with the same images of mineral which we have trained the model.
Since i tested which all types of minerals photos and it accurately predict the mineral for each input image 

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Reduce the number of images files in the Images folder, put at least one file there for each of the minerals.

**Comment by tanuj437** [comment]
@abhisheks008 Reduce the number of images in image folder as well as put the each mineral photo in it too. Can't reduce more images in there

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
The images you have stored in the img folder are the datapoints right? And these same images can be restored from the dataset URL.

Correct me if I am wrong.

**Comment by tanuj437** [comment]
@abhisheks008 yes those are the datapoints which trained the model...img folder in Dataset is actually the dataset folder

**Comment by tanuj437** [comment]
@abhisheks008 All changes Done

**Comment by abhisheks008** [comment]
Upload a demonstration video of the working of the web app and attach the same in the Web App/README, so that others can have an idea about the working of the web app.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved @tanuj437

**Pull request merged**
