### PR TITLE
Emotion recognition in text

### PR DESCRIPTION
**Pull request by SRUJANA2199**
# 586 💡

## Issue Title: Emotion Recognition In Text

- **Info about the related issue (Aim of the project)** : 
- **Name:** SRUJANA
- **GitHub ID:** SRUJANA2199
- **Idenitfy yourself:** contributor in jwoc

Closes: #586

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added things that prove my fix is effective or that my feature works.
- [x ] Any dependent changes have been merged and published in downstream modules.

Fill this up @SRUJANA2199

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Follow the README template and make the README file eye pleasing. Here is the template for your reference, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md
2. Put the Data Visualization/EDA results inside the README.md file.
3. Rename the project folder name as **Emotion Recognition in Text** (Same as the issue name).
4. Rename the README.md file as **README.md** (Incorrect: readme.md)
5. Remove the **Model** folder you have created outside the project folder, which is getting merged directly to the ML-Crate project repository. 
image

@SRUJANA2199 please do the needful changes.

**Comment by SRUJANA2199** [comment]
I have done the changes,do check it out

**Review by abhisheks008 — APPROVED** [review]
Approved under JWOC 2024 Phase 1 @SRUJANA2199

**Comment by abhisheks008** [comment]
Please share your email address for further communication @SRUJANA2199

**Comment by SRUJANA2199** [comment]
imperiousknight72@gmail.com

**Pull request merged**
