### PR TITLE
Quora

### PR DESCRIPTION
**Pull request by yagyesh-bobde**
# Pull Request for ML-Crate 💡

## Issue Title : Quora Insincere Questions Classification Analysis & Prediction

- **Info about the related issue (Aim of the project)** : 
- **Name:** Yagyesh Bobde
- **GitHub ID:** 90238742
- **Idenitfy yourself:** 
   - [x] SWOC Participant ❄️
   - [ ] JWOC Participant ☃️
   - [x] Contributor ✔️

Closes: #109 

### Describe the add-ons or changes you've made 📃

Text preprocessing on the Quora dataset and applying data cleaning, then used embedding and tried varioud models and compared accuracies among them 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
PR approved and merged.

**Comment by yagyesh-bobde** [comment]
error push

This error is showing up when I tried pushing my changes....what should I do ?

**Comment by abhisheks008** [comment]
From the next time, try to push your codes using GitHub webpage version, not by using the terminal one.

**Comment by yagyesh-bobde** [comment]
okay

**Pull request merged**
