### PR TITLE
Milk Quality Prediction #348

### PR DESCRIPTION
**Pull request by shubhammore45**
# Pull Request for ML-Crate 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)**: 
- **Name:** 
- **GitHub ID:** 
- **Identify yourself:** 

Closes: #348 

### Describe the add-ons or changes you've made 📃

Created a model using SVM to predict the quality of Milk. 
## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. The sub directory name should be `Milk Quality Prediction`, no underscores are there.
2. In the `Model/README.md` file, add the visualization images as a part of showcasing your work.
3. Use 3-4 more algorithms for this dataset, and based on the accuracy provide the best fitted one. Using a single model you can't make a comparison.
4. Rename the `requirements.txt.txt` file as `requirements.txt`.
5. You can check out other projects for your reference.

@shubhammore45

**Comment by shubhammore45** [comment]
I have done all the necessary changes, please check.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Finely represented all the things.

Your PR is approved and ready to be merged.
@shubhammore45

**Comment by shubhammore45** [comment]
Thank you @abhisheks008

**Pull request merged**
