### PR TITLE
Pets

### PR DESCRIPTION
**Pull request by yagyesh-bobde**
# Pull Request for ML-Crate 💡

## Issue Title : Pets Images Classification

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Idenitfy yourself:** 
   - [x] SWOC Participant ❄️
   - [x] Contributor ✔️

Closes: #100 

### Describe the add-ons or changes you've made 📃

Image data loading, data preprocessing, and Model selection and training 

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Again same issue @yagyesh-bobde

**Comment by yagyesh-bobde** [comment]
@abhisheks008 I actually just added my project directory and pushed.............. I don't know why it is saying that 56 files changed.... same thing happened with the number plate prediction PR........what should I do?

**Comment by abhisheks008** [comment]
Create a fresh PR and do all the steps from the beginning.

**Comment by yagyesh-bobde** [comment]
I did that, when you closed the last PR.............. I actually cloned the repo again > created a new branch > and directly pasted my project repo > pushed the changes........... but when I created the pull request (in all 3 PRs) its showing the same thing

**Comment by yagyesh-bobde** [comment]
dir
These are all the files that I pushed related to this issue.........other than that I didn't change any file

**Comment by yagyesh-bobde** [comment]
In the last PR too I did this but I tried it again

**Comment by yagyesh-bobde** [comment]
@abhisheks008 I actually tried cloning the repo again ..........but this is what it shows : 
clone


and when I used git status :


status

wheneever I clone these changes already occur............... how shud I deal with this?

**Pull request closed without merging**
