### PR TITLE
BellaBeat - Capstone Project by Google

### PR DESCRIPTION
**Pull request by BhardwajArjit**
# Pull Request for ML-Crate 💡

## Issue Title: BellaBeat - Capstone Project by Google

- **Aim of the project** : The aim of this project is to create a model which will analyze the Bellabeat project.
- **Name:** Arjit Bhardwaj
- **GitHub ID:** BhardwajArjit
- **Idenitfy yourself:** KWOC Contributor

Closes: #248 (partially)

### Describe the add-ons or changes you've made 📃

Till now I have completed the Exploratory Data Analysis and concluded the correlations between various variables. 

## Type of change ☑️

What sort of change have you made:
Exploratory Data Analysis completed

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
No issues so far

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Create a README.md file inside the Dataset folder and share the URL of the dataset. No need to upload all the `.csv` files. Only the URL can help others to understand.
2. Looks good to me till now. Make sure you complete the whole project within the deadline of the event.

**Comment by BhardwajArjit** [comment]
Hi @abhisheks008, I have updated the pull request as per the changes requested. Kindly review it. 
Definitely, I'll complete this project before 9th January 2024. 
Kindly consider this PR for the mid evals.

**Comment by BhardwajArjit** [comment]
Hi Abhishek,

I have updated PR with changes requested. Kindly review it.

**Comment by abhisheks008** [comment]
Looks good to me. Proceed with the models once you are ready to do it. I will not merge this PR as of now, make the whole project and update it here. I have noted your work for the mid evaluations.

**Comment by BhardwajArjit** [comment]
Sure. Thanks a lot.

**Comment by BhardwajArjit** [comment]
Hi @abhisheks008, I have updated the PR with the models. Please review the whole project.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Your PR is approved and ready to be merged.
@BhardwajArjit

**Pull request merged**
