### PR TITLE
[README Enhancement]: Advertisement Click Prediction

### PR DESCRIPTION
**Pull request by imsuraj675**
# Pull Request for ML-Crate 💡

## Issue Title: [README Enhacement]: Advertisement Click Prediction #598

Enhanced the README file
- Name: Suraj Kashyap
- GitHub ID:[https://github.com/imsuraj675](https://github.com/imsuraj675)
- Idenitfy yourself: Participant in SSOC'24

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — APPROVED** [review]
Approved @imsuraj675

**Comment by abhisheks008** [comment]
Hi @imsuraj675 please share your email address for further communications.

**Comment by abhisheks008** [comment]
> Hi @imsuraj675 please share your email address for further communications.

Share it ASAP @imsuraj675

**Comment by imsuraj675** [comment]
> > Hi @imsuraj675 please share your email address for further communications.
> 
> Share it ASAP @imsuraj675

My email address for SSOC'24 is imsuraj675@gmail.com
My email address linked to the github is techjk021@gmail.com

**Pull request merged**
