### PR TITLE
F1 Visa Experiences

### PR DESCRIPTION
**Pull request by stackaway**
# Pull Request for ML-Crate 💡

## Issue Title: 

- **Info about the related issue (Aim of the project)** :  Finding out if the review is positive, negative or neutral. 
- **Name:** Churnika S Mundas
- **GitHub ID:** [stackaway ](https://github.com/stackaway)
- **Idenitfy yourself:** JWOC'24 Contributor

Closes: #128 
### Describe the add-ons or changes you've made 📃

Preprocessed the dataset that is given and proceeded to using Logistic Regression, Random Forest Classifier and SVM models and SVM had the highest accuracy followed by Random Forest Classifier.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Changes have been tested by plotting graphs and seeing the level of accuracy attained on validation dataset using various models.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by stackaway** [comment]
@abhisheks008 please review this pr and requested to merge it under JWOC'24

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Remove the `.DS_Store` file.
@stackaway

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
.DS_Store is still there.

**Comment by stackaway** [comment]
there were 2  .DS_Store files, I was able to delete one, the other I am unable to figure out how to delete. @abhisheks008 can you pls help me out with how I can proceed

**Comment by abhisheks008** [comment]
> there were 2 .DS_Store files, I was able to delete one, the other I am unable to figure out how to delete. @abhisheks008 can you pls help me out with how I can proceed

Can you make a fresh PR for this project after deleting the files from your end.

**Pull request closed without merging**
