### PR TITLE
Human Dataset Visualization

### PR DESCRIPTION
**Pull request by SOMNATH0904**
# Pull Request for ML-Crate 💡

## Issue Title: Human Dataset Visualization

- **Info about the related issue (Aim of the project)** :  To visualize and analyze the Human3.6M dataset to gain insights into 3D human poses and movements.
- **Name:**  Somnath Shaw
- **Email ID for further communication**:  somnath.arcade3.2024@gmail.com
- **GitHub ID:**  https://github.com/SOMNATH0904
- **Idenitfy yourself:**  Student

Closes: #722 

### Describe the add-ons or changes you've made 📃
The Human3.6M dataset aims to provide a comprehensive resource for understanding human poses and movements. It includes a large collection of 3D human motion data captured in a controlled environment.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
The files are updated.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Rename the project folder as per the issue name with no underscore.

**Comment by SOMNATH0904** [comment]
@abhisheks008 Updated 

> Rename the project folder as per the issue name with no underscore.

**Comment by abhisheks008** [comment]
What have you visualized? No Jupyter notebook file, no EDA results, please update the pull request.
@SOMNATH0904

**Comment by abhisheks008** [comment]
Can't provide more time. Closing this pull request as not done.

**Comment by SOMNATH0904** [comment]
> Can't provide more time. Closing this pull request as not done.

@abhisheks008 Okay, No problem. Actually, I am working in this. So, It will take some time. Thank you!

**Pull request closed without merging**
