### PR TITLE
Added Face Mask Detection

### PR DESCRIPTION
**Pull request by srini047**
# Pull Request for ML-Crate 💡

## Issue Title: Face Mask Detection

- **Info about the related issue (Aim of the project)** : Detect the face mask using a machine learning approach.
- **Name:** Sriniketh J
- **GitHub ID:** [srini047](https://github.com/srini047/)
- **Idenitfy yourself:** 
 
   - [x] JWOC Participant ☃️
   - [x] Contributor ✔️

**Closes:** #137 

### Describe the add-ons or changes you've made 📃

Added project folder as per the suggested template.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

Ran the Jupyter Notebook from start to end with any error or code breaks.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
@srini047 in the Dataset folder put the link of the dataset only in the `Dataset/README.md` file. No need add different files, these are making the repo heavier. Just remove them.

**Comment by srini047** [comment]
> @srini047 in the Dataset folder put the link of the dataset only in the `Dataset/README.md` file. No need add different files, these are making the repo heavier. Just remove them.

Sure will do the needful.

**Comment by srini047** [comment]
I have done the changes please review it @abhisheks008

**Comment by abhisheks008** [comment]
Perfect work @srini047

**Pull request merged**
