### PR TITLE
Bpl analysis

### PR DESCRIPTION
**Pull request by VishnuBhaarath**
## Bangladesh Premier League Analysis:

- Analyze and visualize the matches of BPL for the 2021-22 season

- [ ] JWOC Participant

- **Vishnu Bhaarath K.N**
- **VishnuBhaarath**

(Mention these details are must)

Closes: #184 

### Describe the add-ons or changes you've made

Have performed analysis on the dataset using python.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
@VishnuBhaarath while you are making your PR make sure you fill the form properly, otherwise what's the purpose providing the template! You just need to put the tick in the checkboxes. This is how it works,
```
- [x] JWOC Participant
```
It results like this, 
- [x] JWOC Participant

Please keep this in mind for the next PRs.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Inside the `Dataset/README.md` file, mention the details about the datasets, and also provide the URL from where you are downloading the dataset.

**Comment by VishnuBhaarath** [comment]
> @VishnuBhaarath while you are making your PR make sure you fill the form properly, otherwise what's the purpose providing the template! You just need to put the tick in the checkboxes. This is how it works,
> 
> ```
> - [x] JWOC Participant
> ```
> 
> It results like this,
> 
> * [x]  JWOC Participant
> 
> Please keep this in mind for the next PRs.

yeah sure will do so

**Comment by VishnuBhaarath** [comment]
> Inside the `Dataset/README.md` file, mention the details about the datasets, and also provide the URL from where you are downloading the dataset.

Have made the changes

**Review by abhisheks008 — APPROVED** [review]

**Pull request merged**
