### PR TITLE
Critically Ill Patients Analysis and Prediction Model

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Pull Request for ML-Crate 💡

## Issue Title: Critically Ill Patients Analysis and Prediction

- **Info about the related issue (Aim of the project)** : Create a bunch of ML models to analyze the critically ill patients and predict their future.
- **Name:** Avdhesh Varshney
- **GitHub ID:** Avdhesh-Varshney
- **Idenitfy yourself:** Contributor

Closes: #466 

### Describe the add-ons or changes you've made 📃

* Load the dataset which contains 9105 entries in it and having 47 columns in it.
* Checked for missing values and cleaned the data accordingly.
* Analyzed the data, found insights and visualized them accordingly.
* Plotting heatmap using correlation and checking the relation between different features.
* Found detailed insights of different columns with target variable using plotting libraries.
* Train the datasets by different models and saves their accuracies into a dataframe.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

- I have made this project on the google colab.
- So, just download the file and run it by linking `kaggle.json` in the drive.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please review this pr and requested to merge this pr under IWOC'24

**Comment by abhisheks008** [comment]
> @abhisheks008 please review this pr and requested to merge this pr under IWOC'24

You can put this in the PR template, where it asked you to identify yourself.

**Review by abhisheks008 — APPROVED** [review]
Really appreciated. Approved.
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
> Really appreciated. Approved. **Share your email ID for further communication in Discord.** @Avdhesh-Varshney

@abhisheks008 thanks for approving this pr and i have updated the pr template.
Email ID - avdheshvarshney786@gmail.com

**Pull request merged**
