### PR TITLE
Sleep Health and Lifestyle Dataset Analysis

### PR DESCRIPTION
**Pull request by Sgvkamalakar**
# Pull Request for ML-Crate 💡

## Issue Title: Sleep Health and Lifestyle Dataset Analysis

- **Info about the related issue (Aim of the project)**: This project aims to predict sleep disorders based on various health metrics and lifestyle factors.
- **Name:** S G V Kamalakar
- GitHub ID: [Sgvkamalakar](https://github.com/Sgvkamalakar)

- Identify yourself: SSOC  S3

Closes: #512 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

### Describe how have you verified the changes made

Conducted a thorough code review to ensure the changes aligned with the project goals and coding standards. You can run the [notebook](https://colab.research.google.com/drive/1iUNcDuqsTgx5Z3DtTeSxpK-LcyfBJE0Z?usp=sharing)

**Models performance comparison**

img

**Streamlit App - Sleep Disorder Prediction page**

image

**Streamlit App - EDA and Visualization page**

image

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — APPROVED** [review]
Approved @Sgvkamalakar

**Comment by Sgvkamalakar** [comment]
Thanks @abhisheks008  🎉

**Comment by abhisheks008** [comment]
Hi @Sgvkamalakar please share your email address for further communications.

**Comment by Sgvkamalakar** [comment]
> Hi @Sgvkamalakar please share your email address for further communications.

sgvkamalakar@gmail.com

**Pull request merged**
