### PR TITLE
Forbes Billionaire Data Analysis

### PR DESCRIPTION
**Pull request by pawaspy**
# Pull Request for ML-Crate 💡

## Issue Title: 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Idenitfy yourself:** 

Closes: #496 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Enhancing means updating/upgrading the existing project in terms of models, EDA and visualization of the existing dataset. You have created a separate project, that's not enhancement means. That's why I told you while taking the issue and I have also given you the link of the existing project for your reference. You need to work on with the existing project mentioned in the issue by me, upgrade with fine tuned models instead of the existing ones, try to conclude more points with your analysis skills and make the existing project more capable.

@pawaspy

**Comment by pawaspy** [comment]
@abhisheks008 So I have to make changes in the old juoyter file. But in that the dataset is changed and I have to add in that juoyter file?!

**Comment by abhisheks008** [comment]
> @abhisheks008 So I have to make changes in the old jupyter file. But in that the dataset is changed and I have to add the models that I created in that jupyter file or do I have to create a new file

Use the existing project's dataset and make the changes to upgrade the existing models.

**Comment by abhisheks008** [comment]
Close due to inactivity.

**Pull request closed without merging**
