### PR TITLE
Car Image classifier

### PR DESCRIPTION
**Pull request by PARKER-X**
# Pull Request for ML-Crate 💡

## Issue Title : Create a new project

Project goal is to create car image classifier for car ecommerce website to predict car or not
- Name:   Parker-x
- GitHub ID:    https://github.com/PARKER-X
- 

Closes: #362

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

Create a new ml  project

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by PARKER-X** [comment]
I closed my old pull request

**Comment by abhisheks008** [comment]
Please mention the issue number, you have tagged the PR itself in this PR @PARKER-X

**Comment by PARKER-X** [comment]
Issue number 362

**Comment by abhisheks008** [comment]
I have asked the issue number not the PR number, as you have not been assigned to any of the issues of ML-Crate.
Can you tell me which open source program you are participating in?
@PARKER-X

**Comment by PARKER-X** [comment]
Issue number 354 , I'm new to open source. can u share some resource how to start open source. sorry for wasting your time.

**Comment by abhisheks008** [comment]
I am sorry there are no such issue as 354 @PARKER-X.

⚙️ Can you please mention the open source program, through which you are trying to contribute in **ML-Crate Project Repo** or, you just randomly selected this project repo without being a part of any open source program. 

📌 And for the resources related to Open source programs, how open source works, here are few resources you can check them out, 
1. **How to start with Open Source** : https://www.youtube.com/watch?v=yzeVMecydCE
2. **How to start with Git and GitHub** : https://youtube.com/playlist?list=PLO_Y0rsm7b3aubpJhA6Td7af9Vjk0mDAm
3. Try to explore the Internet, you'll get an idea of this.

Best wishes ✨

🔴 As this pull request is invalid in the context of **ML-Crate Project Repo**, I am closing this. Sorry for that.

**Pull request closed without merging**
