### PR TITLE
Poker Hand Prediction

### PR DESCRIPTION
**Pull request by aviralgarg05**
# Pull Request for ML-Crate 💡

## Issue Title:  Poker Hand Prediction

- **Info about the related issue (Aim of the project)** :  Predict Poker Hand
- **Name:**  Aviral Garg
- **Email ID for further communication**:  gargaviral99@gmail.com
- **GitHub ID:**  aviralgarg05
- **Idenitfy yourself:**  SSOC Contributor

Closes: #issue number that will be closed through this PR
 #693 
### Describe the add-ons or changes you've made 📃
NA
Give a clear description of what have you added or modifications made
NA
## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested: Previous Test Datasets
Describe how have you verified the changes made:- Accuracy Scores

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have created duplicate folders inside the project folder. Please go through them and make them arranged.

@aviralgarg05

**Comment by aviralgarg05** [comment]
Ok I will edit them out

**Comment by abhisheks008** [comment]
Still the duplicate files are present in the project folder. Also use a generalized Jupyter Notebook file instead of separate `.py` files for each of the algorithms. Create an `.ipynb` file and do the EDA, model training, model implementations one after another. That'll be easier to understand for any one.

**Comment by aviralgarg05** [comment]
> Still the duplicate files are present in the project folder. Also use a generalized Jupyter Notebook file instead of separate `.py` files for each of the algorithms. Create an `.ipynb` file and do the EDA, model training, model implementations one after another. That'll be easier to understand for any one.


Actually those are the models that I created separately, and called them into the ipynb for visualization and testing purposes. (It was giving me some kernel issues while training the models in jupyter notebook so created them separately as .py and called them in .ipynb for testing). The files present in both the folders are completely different. Just their naming is same for identification purposes of models while calling.

**Comment by abhisheks008** [comment]
Why should we have `.ipynb` and `.py` files for each and every algorithm? These are simple machine learning algortihms I don't think these will take too much of the kernel for processing.

**Comment by aviralgarg05** [comment]
> Why should we have `.ipynb` and `.py` files for each and every algorithm? These are simple machine learning algortihms I don't think these will take too much of the kernel for processing.

No it wasn't taking resources, but was giving me virtual environment issues while training about the libraries. So created model separately and tested separately. Actually I had been working on different project and some issues of kernel versions had been occurring.

**Comment by abhisheks008** [comment]
Hi @aviralgarg05 I got your points. But it's better to go with a single jupyter notebook file which will contain all the stuff including the EDAs, model training and model implementation.

**Comment by aviralgarg05** [comment]
What I'll do is add the entire folder to .gitignore Hence it would make the structure better. As without those files the actual prediction won't work.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Follow the README template and update the README. Here it is, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md
2. Rename the `.ipynb` folder from "Poker Hand Prediction" to "Notebooks".

@aviralgarg05

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved ✅ 
@aviralgarg05

**Pull request merged**
