### PR TITLE
Nuclear weapons analysis

### PR DESCRIPTION
**Pull request by adi271001**
# Pull Request for ML-Crate 💡

## Issue Title:  #392 Nuclear Weapon Analysis and Classification

- **Info about the related issue (Aim of the project)** : 
- **Name:**  Aditya D
- **GitHub ID:**  adi271001
- **Idenitfy yourself:**  Contributor KWOC

Closes: #issue number that will be closed through this PR #392

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Added new folder nuclear weapons analysis and classification, all requirements satisfied

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Divided Datasets into test and train 20% as test 80 % as train 7 distinct models used

Describe how have you verified the changes made
plotted graphs which is present in images folder which prove that models haven't been under or overfitted

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Folder name should be, **Nuclear Weapon Analysis**, instead of `Nuclear-Weapons-Analysis-And-Classification`. Update the folder name, and you are good to go!

@adi271001

**Comment by adi271001** [comment]
renamed folder

**Comment by abhisheks008** [comment]
image
Images are not visible.

**Comment by adi271001** [comment]
@abhisheks008 now its visible

**Comment by abhisheks008** [comment]
Approved.

**Review by abhisheks008 — APPROVED** [review]

**Pull request merged**
