### PR TITLE
Singaporean Cryptocurrency Analysis Completed

### LINKED ISSUE #476: Singaporean Cryptocurrency Analysis
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Singaporean Cryptocurrency Analysis
:red_circle: **Aim** : Create a machine learning model to analyze the dataset of Singaporean Cryptocurrency.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/imperialwarrior/singapore-crypto
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Pull Request for ML-Crate 💡

## Issue Title:  Singaporean Cryptocurrency Analysis

- **Info about the related issue (Aim of the project)** : Create a machine learning model to analyze the dataset of Singaporean Cryptocurrency.
- **Name:** Avdhesh Varshney
- **GitHub ID:** https://github.com/Avdhesh-Varshney
- **Idenitfy yourself:** Contributor

Closes: #issue number that will be closed through this PR
closes #476 

### Describe the add-ons or changes you've made 📃

* Checked for first dataset values out of 7537 datasets.
* Checked for missing values and cleaned the data accordingly.
* Analyzed the data, found insights and visualized them accordingly.
* Found detailed insights of different columns with target variable using plotting libraries.
* Train the datasets by different models and saves their accuracies into a dataframe.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please review this pr and requested to merge this pr under KWOC

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and put your files accordingly. You can check other projects present here in this repo.
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please again review this pr and requested to merge this pr under KWOC

**Review by abhisheks008 — APPROVED** [review]
Looks good to me! Your PR is approved and ready to be merged.
@Avdhesh-Varshney

**Comment by abhisheks008** [comment]
Hi @Avdhesh-Varshney can you share your email with me in Discord for further communication regarding the KWOC event?

**Comment by abhisheks008** [comment]
@Avdhesh-Varshney share your email ID

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney share your email ID

@abhisheks008 
Email - avdheshvarshney786@gmail.com

**Pull request merged**
