### PR TITLE
Created Email Spam Classifier

### PR DESCRIPTION
**Pull request by codewithpiyushh**
# Pull Request for ML-Crate 💡

## Issue Title:  End to End Email spam classifier

- **Info about the related issue (Aim of the project)** : 
- **Name:**  Piyush
- **GitHub ID:**  https://github.com/codewithpiyushh
- **Idenitfy yourself:**  Contributor SSOC

Closes: #614  #issue number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

machine learning model that classifies emails as spam or not spam. It leverages Python and popular libraries like scikit-learn to train and evaluate various classification algorithms. The model aims to identify spam emails with high accuracy, protecting users from unwanted content.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Project folder name should be same as the issue name with no hyphens.
2. Create a README file inside the Web App folder and follow the [template](https://github.com/abhisheks008/ML-Crate/blob/main/.github/web-app-readme-template.md). Add a demonstration video of the working of the web app and add that inside the README of the web app.
3. Follow the README template and update the README of the Models folder accordingly. Here is the template, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md
4. For your reference, follow this project's structure [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection). Look at the files pushed in the project and update the same in your project folder too.

Need these changes @codewithpiyushh

**Review by abhisheks008 — APPROVED** [review]
Approved @codewithpiyushh

**Comment by abhisheks008** [comment]
Hi @codewithpiyushh please share your email address for further communications.

**Comment by codewithpiyushh** [comment]
my email is piyushhhsinghh@gmail.com

**Pull request merged**
