### PR TITLE
PubMed Text Classification MeSH Model

### PR DESCRIPTION
**Pull request by adi271001**
# Pull Request for ML-Crate 💡

## Issue Title:  #249 

- **Info about the related issue (Aim of the project)** :  to classify pubmed articles
- **Name:**  Aditya D
- **GitHub ID:**  adi271001
- **Idenitfy yourself:**  IWOC 2024

Closes: #issue number that will be closed through this PR #249 

### Describe the add-ons or changes you've made 📃
Added files and model notebook as per rules

Give a clear description of what have you added or modifications made
added images , results , dataset description , model file and description , requirements

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by adi271001** [comment]
@abhisheks008 to view the weights and biases dashboard i have invited you via email

**Review by abhisheks008 — APPROVED** [review]
Approved under IWOC 2024 @adi271001

**Comment by abhisheks008** [comment]
@adi271001 please share your email address for further communication.

**Comment by adi271001** [comment]
This is my email Ibetanibex@gmail.com

**Pull request merged**
