### PR TITLE
Spam detection

### PR DESCRIPTION
**Pull request by yagyesh-bobde**
## Issue Title : Spam Email Detection

- Info about the related issue (Aim of the project)

- [x] SWOC Participant 
- [x] Contributor

Closes: #21

### Describe changes you've made

Created a spam email detection model using the spambase dataset.

## Checklist:
- [x] My code follows the code style of this project.
-->
- [x ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x ] My changes generate no new warnings.

### CODE REVIEW

**Comment by yagyesh-bobde** [comment]
I have completed it ..... plz take a look at it @abhisheks008

**Comment by abhisheks008** [comment]
@yagyesh-bobde remove the .ds store files, those are unnecessary.

**Comment by yagyesh-bobde** [comment]
done

**Comment by abhisheks008** [comment]
@yagyesh-bobde there are other .ds store files in different folders, delete them too.

**Comment by yagyesh-bobde** [comment]
I think i deleted all of them .... sry I had something else to do so got delayed

**Comment by abhisheks008** [comment]
Good work @yagyesh-bobde

**Pull request merged**
