### PR TITLE
Global Emission Analysis Project

### PR DESCRIPTION
**Pull request by minal2577**
# Pull Request for ML-Crate 💡

## Issue Title: 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Idenitfy yourself:** 

Closes: #500 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

I have tested the notebook by running all the cells to ensure there are no errors. Each step in the notebook, from data preprocessing to policy impact simulation, was verified for correctness and functionality.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by minal2577** [comment]
Good evening,

I have created a project for issue #500 using air and climate data. In this project, I refined the data and applied the algorithms as discussed. However, I believe that the model would benefit from further data training to improve its accuracy and performance.

Best regards,
minal(minal2577)

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please update the project structure and put your files as per the structure. You need to create a single project folder as "Global Emission Analysis", inside that you need to create Model, Images, Dataset folders and put the files as per their folder specifications.
@minal2577

**Comment by abhisheks008** [comment]
> # Pull Request for ML-Crate 💡
> ## Issue Title:
> * **Info about the related issue (Aim of the project)** :
> * **Name:** <!--Minal->
> * **Email ID for further communication**:
> * **GitHub ID:**
> * **Idenitfy yourself:**
> 
> Closes: #500
> 
> ### Describe the add-ons or changes you've made 📃
> Give a clear description of what have you added or modifications made
> 
> ## Type of change ☑️
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> ## How Has This Been Tested? ⚙️
> I have tested the notebook by running all the cells to ensure there are no errors. Each step in the notebook, from data preprocessing to policy impact simulation, was verified for correctness and functionality.
> 
> ## Checklist: ☑️
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly wherever it was hard to understand.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have added things that prove my fix is effective or that my feature works.
> * [x]  Any dependent changes have been merged and published in downstream modules.

Please fill up this template while you are creating a pull request. This will help me to understand the contributor and the issue details.

**Comment by minal2577** [comment]
Good evening,
I have made the required changes. The final data used is in the "data preparing and cleaning" section. Should I add this to the dataset?
Thank you.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Remove `gitattributes` and `gitignore` files.
2. Create a folder as Images and upload the images inside that folder.
3. The subfolder names should be like this, Dataset, Images, Models.
4. Remove the zip file.
5. Add the README using the given template.
6. Project folder name should be in Title case.
7. `requirement.txt` should be renamed as `requirements.txt`.

@minal2577

**Comment by minal2577** [comment]
Sir i have made asked changes please tell me if any another change is needed

**Review by abhisheks008 — APPROVED** [review]
Hi @minal2577 looks good to me. Approved ✅

**Comment by abhisheks008** [comment]
@minal2577 how many times should I inform you to update youre= details as per the pull request, I have mentioned twice to fill up the details still you are acting carelessly, without your details how can I add your points in the system?

**Comment by minal2577** [comment]
Sir i have already done it from my side may be there is a technical issue it shows from my side its done

**Comment by abhisheks008** [comment]
@minal2577 put your details as per the template in the comments.

**Comment by minal2577** [comment]
Done sir  see if you are able to see it

**Pull request merged**
