### PR TITLE
Narendra Modi - Text Speeches Analysis

### PR DESCRIPTION
**Pull request by HarshRaj29004**
# Pull Request for ML-Crate 💡

## Issue Title: Narendra Modi - Text Speeches Analysis

- **Info about the related issue (Aim of the project)** : This project is to analyze the speeches of Narendra Modi.
- **Name:** Harsh Raj
- **Email ID for further communication**: 
- **GitHub ID:**[ ](https://github.com/HarshRaj29004)
- **Idenitfy yourself:** SSOC'24 participant

Closes: #127

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:
** Analysis the speeches as per in the dataset and concluded few of the points from it.**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by HarshRaj29004** [comment]
Major are done in the duration of cloning. Few of the files were showing errors.

**Comment by abhisheks008** [comment]
image

You shouldn't have updated the existing files.

**Comment by HarshRaj29004** [comment]
I have restored some deleted png files and none file have been modified.

**Comment by abhisheks008** [comment]
Hi @HarshRaj29004 but in GitHub it's showing that you might have done some updates to the existing projects. It might occur if you are not pushing your code in the latest forked repository. It'll be better if you create a fresh PR for the same with the latest forked repository.

**Pull request closed without merging**
