### PR TITLE
Blood donation analysis

### PR DESCRIPTION
**Pull request by hemant933**
# Pull Request for ML-Crate 💡

## Issue Title:  Blood donation analysis

- **Info about the related issue (Aim of the project)** : Create a model that can accurately predict which donors are likely to donate blood again.
- **Name:**Hemant Chaudhary
- **GitHub ID:**  github.com/hemant933 
- **Idenitfy yourself:**  ML enthusiast 
-**email:** chaudharyhemant933@gmail.com

Closes: #438 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x ] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added things that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

 this is under IWOC24

### CODE REVIEW

**Review by abhisheks008 — APPROVED** [review]
Approved.
@hemant933

**Comment by abhisheks008** [comment]
Fill up the pull request template with your credentials along with your email ID for further communication purposes.
@hemant933

**Comment by hemant933** [comment]
> Fill up the pull request template with your credentials along with your email ID for further communication purposes. @hemant933

done sir

**Comment by abhisheks008** [comment]
Hi @hemant933 this is the first time you are contributing in this project repository, I know the difficulties you faced during the contribution. Try to do better in the next contribution, you can check out this project, this is near perfect one, https://github.com/abhisheks008/ML-Crate/tree/main/Critically%20Ill%20Patients%20Analysis%20and%20Prediction for your reference. 

Best wishes! Keep contributing.

**Pull request merged**
