### PR TITLE
F1 Visa Experiences

### PR DESCRIPTION
**Pull request by stackaway**
# Pull Request for ML-Crate 💡

## Issue Title:  F1 Visa Experiences

- **Info about the related issue (Aim of the project)** : Finding out if the review is positive, negative or neutral.
- **Name:** Churnika S Mundas
- **GitHub ID:** (https://github.com/stackaway)
- **Idenitfy yourself:** JWOC 2024 Contributor

Closes: #128 

### Describe the add-ons or changes you've made 📃
 
We analyse the data, preprocess and visualize the features. We then investigated two predictive models. The data was split into two parts, a train set and a test set.

We started with Logistic Regression, Random Forest Classifier and SVM and SVM had the highest accuracy followed by Random Forest Classifier.

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Logistic Regression, Random Forest Classifier and SVM and SVM had the highest accuracy followed by Random Forest Classifier.

## Checklist: ☑️

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the template and update the README file to make it eye pleasing. (Suggestion: Add the EDA results under the Visualization tag). Here is the template, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

**Comment by stackaway** [comment]
I have updated the README file

**Review by abhisheks008 — APPROVED** [review]
Approved under JWOC 2024 @stackaway

**Comment by abhisheks008** [comment]
Hi @stackaway can you please share your email ID for further communication.

**Comment by abhisheks008** [comment]
Hi @stackaway can you please share your email ID for further communication.

**Comment by stackaway** [comment]
churnika.mundas@gmail.com

**Pull request merged**
