### PR TITLE
Cement Strength Prediction

### PR DESCRIPTION
**Pull request by adi271001**
# Pull Request for ML-Crate 💡

## Issue Title: 

- **Info about the related issue (Aim of the project)** :  To predict strength of cement using ml models
- **Name:**  Aditya D
- **Email ID for further communication**:  ibetanibex@gmail.com
- **GitHub ID:**   https://www/github.com/adi271001
- **Idenitfy yourself:** SSOC Contributor

Closes: #issue number that will be closed through this PR #647

### Describe the add-ons or changes you've made 📃 

Give a clear description of what have you added or modifications made
i have added the folder containing models , datasets and images for cement strength prediction i have used 8 models catboost was best among them

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made
i have tested by dividing the dataset into train and test dataset and have also checked for over/underfitting
## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
You have already put the result images in the images folder, no need to upload duplicate images again.
Remove the duplicate files. Also remove the `catboost_info` and `learn` folder`.

**Comment by adi271001** [comment]
@abhisheks008 i have deleted please do check

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the README template and update the same for your project.

Template: https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

**Comment by adi271001** [comment]
i have correted it please do check @abhisheks008

**Review by abhisheks008 — APPROVED** [review]
Approved @adi271001

**Pull request merged**
