### PR TITLE
Health Insurance Cross Sell Prediction

### PR DESCRIPTION
**Pull request by tanuj437**
# Pull Request for ML-Crate 💡

## Issue Title: Health Insurance Cross Sell Prediction

- **Info about the related issue (Aim of the project)** : To Predict the Customer response will they be buying Insurance or not based on past and vehicle data
- **Name:** Tanuj Saxena
- **Email ID for further communication**: tanuj.saxena.rks@gmail.com
- **GitHub ID:** https://github.com/tanuj437
- **Idenitfy yourself:** Contributor SSOC'24

Closes: #706 number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

So initially i have done the basic EDA and to check the correlation and distribution of data. Based on the Description and info of column have converted then into standard format for model fitting. Then Fitted the model in 7 models where all get similar accuracy 88% major difference where only in f1, precision value. 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

So for testing i took one data set example from the dataset itself of test.csv which data havn't shown to the model for evaluation and it correct predicted the response

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by tanuj437** [comment]
@abhisheks008 tried more model but none of them crossing 89% that highest i could reach...
any other way if you know i can go that way too

**Comment by abhisheks008** [comment]
> @abhisheks008 tried more model but none of them crossing 89% that highest i could reach... any other way if you know i can go that way too

Have you tried after hyperparameter tuning?

**Comment by tanuj437** [comment]
> > @abhisheks008 tried more model but none of them crossing 89% that highest i could reach... any other way if you know i can go that way too
> 
> Have you tried after hyperparameter tuning?

yes i did that and also tried reducing few features also

**Review by abhisheks008 — APPROVED** [review]
Anyways thanks for trying to make it better.
Approving this pull request @tanuj437

**Pull request merged**
