### PR TITLE
HOUSE PRICE PREDICTION

### PR DESCRIPTION
**Pull request by Vanshikagoel0012**
## Issue Title #7 

- Info about the related issue (Aim of the project)

- [x] SWOC Participant 
- [ ] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the proper workflow and folders for any of the project. You can take reference from others' projects which have been merged into this repo.

@Vanshikagoel0012

**Comment by abhisheks008** [comment]
@Vanshikagoel0012 Please do the required changes.

**Comment by Vanshikagoel0012** [comment]
Will do it by tomorrow

**Comment by abhisheks008** [comment]
@Vanshikagoel0012 any update?

**Comment by abhisheks008** [comment]
I am sorry to inform you that you've been unassigned from this issue and this PR will not be able close the respective issue.

**Pull request closed without merging**
