### PR TITLE
Anime Data Analysis and Prediction

### PR DESCRIPTION
**Pull request by PiyushBL45t**
# Pull Request for ML-Crate 💡

## Issue Title: Anime Data Analysis and Prediction

- **Info about the related issue (Aim of the project)**: To analyze the behavior of various Animes and predict the future demand of some Genres using Rating as a parameter.
- **Name:**: Piyush Bhujbal
- **GitHub ID:** https://www.github.com/PiyushBL45t
- **Idenitfy yourself:**: HSOC Participant
- Closes: #275 

### Describe the add-ons or changes you've made 📃
1. Extracted all the features from the original dataset.
2. Selected the genre types for analysis and prediction.
3. Created dummy variables for the features.
4. Made data visualizations.
5. Created the data frame as new_data from the extracted features.
6. Separated the dependent and independent variables.
7. Splitted the train and test models.
8. Implemented the ML models

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️
In the extracted data: 
1. Implemented three ML models:
     1. Linear Regression
     9. Random Forest Regressor
     10. Decision Tree Regressor
2. Trained the models with respect to the "Rating parameter" for two random Genre types.
3. Printed the training scores and metrics. 
11. Observed the model stability using the normal distribution.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Your visualizations in the README.md file is not visible, I think there is a hyperlink error occurring. Please check it @PiyushBL45t

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
```
<img src = "https://github.com/PiyushBL45t/ML-Crate/blob/main/Anime%20Data%20Analysis%20and%20Prediction/Images/Screenshot%20(46).png"/>
<img src = "https://github.com/PiyushBL45t/ML-Crate/blob/main/Anime%20Data%20Analysis%20and%20Prediction/Images/Screenshot%20(47).png"/>
<img src = "https://github.com/PiyushBL45t/ML-Crate/blob/main/Anime%20Data%20Analysis%20and%20Prediction/Images/Screenshot%20(48).png"/>
<img src = "https://github.com/PiyushBL45t/ML-Crate/blob/main/Anime%20Data%20Analysis%20and%20Prediction/Images/Screenshot%20(50).png"/>
<img src = "https://github.com/PiyushBL45t/ML-Crate/blob/main/Anime%20Data%20Analysis%20and%20Prediction/Images/Screenshot%20(51).png"/>
```

The links you have put in the README.md file are not valid, goto Images folder and then copy the URL of that particular image and then put it here in the README.md

**Comment by abhisheks008** [comment]
Hey @PiyushBL45t, please do the needful changes otherwise I can not carry forward with this.

**Comment by PiyushBL45t** [comment]
Yes

**Comment by abhisheks008** [comment]
@PiyushBL45t thanks bro 🚀

**Pull request closed without merging**
