### PR TITLE
Gender Recognition By Voice Model

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Pull Request for ML-Crate 💡

## Issue Title: Gender Recognition By Voice

- **Info about the related issue (Aim of the project)** : Create a machine learning project for predicting the voice based on their genders.
- **Name:** Avdhesh Varshney
- **GitHub ID:** https://www.github.com/Avdhesh-Varshney
- **Idenitfy yourself:** KWOC Contributor

Closes: #475 

### Describe the add-ons or changes you've made 📃
* Load the dataset which contains 5993 entries in it and having 22 columns in it.
* Checked for missing values and cleaned the data accordingly.
* Analyzed the data, found insights and visualized them accordingly.
* Plotting heatmap using correlation and checking the relation between different features.
* Found detailed insights of different columns with target variable using plotting libraries.
* Train the datasets by different models and saves their accuracies into a dataframe.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️
- Adding the dataset link just install the requirements.txt dependencies and start the model.
- Second method, i have made this model on google colab so just upload the file and link your kaggle.json file and run all the cells with GPU.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please review this pr and requested to merge this pr under KWOC'23

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the project structure, add the Images folder. Update it properly.
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
> Follow the project structure, add the Images folder. Update it properly. @Avdhesh-Varshney

@abhisheks008 please again review this pr and requested to merge this pr under KWOC'23

**Review by abhisheks008 — APPROVED** [review]
Approved.
@Avdhesh-Varshney 

Please share your email id for further communication.

**Comment by Avdhesh-Varshney** [comment]
> Approved. @Avdhesh-Varshney
> 
> Please share your email id for further communication.

Thanks for approving this pr.
Email Id - avdheshvarshney786@gmail.com

**Pull request merged**
