### PR TITLE
McDonalds India Menu Nutrition Analysis File

### PR DESCRIPTION
**Pull request by Nirvik07**
# Pull Request for ML-Crate 💡

## Issue Title : McDonalds India Menu Nutrition Analysis

- **Info about the related issue (Aim of the project)** : To analyze the nutrition chart from the menu.
- **Name:** NIRVIK GHOSH
- **GitHub ID:** @Nirvik07 
- **Idenitfy yourself:** HRSoC 2022 Participant.

Closes: #123

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Everything looks good, except a typo in your Notebook and also in your README.md. In the conclusion you have written `three models are created`, but actually that's not three.

I can suggest you something through which you can represent that portion, where you have mentioned the models using bullet points. You can do it like this,

| Sl. No. | Models | Accuracy Scores |
|---|---|---|
| 1 | GradientBoosting Regression Algorithm | 0.99 |
| 2 | AdaBoot Regression Algorithm | 0.99 |
| . | . | . |
| . | . | . |
| . | . | . |
| 7 | Bagging Regression Algorithm | 0.94 |


🔴 **Code Snippet:**
```md
| Sl. No. | Models | Accuracy Scores |
|---|---|---|
| 1 | GradientBoosting Regression Algorithm | 0.99 |
| 2 | AdaBoot Regression Algorithm | 0.99 |
| . | . | . |
| . | . | . |
| . | . | . |
| 7 | Bagging Regression Algorithm | 0.94 |
```

In the notebook file it fully supports markdown writings, so you can represent in this compact way. You can use it even when you are editing your README.md file.

@Nirvik07

**Comment by Nirvik07** [comment]
Should I use afresh PR or do thr changes in this PR only.

**Comment by abhisheks008** [comment]
You can do the changes here also, no need to create a fresh one.

@Nirvik07

**Comment by Nirvik07** [comment]
But I think the Conclusion in the  .ipynb file can't be changed until I make a fresh PR. So should I do the changes only in the readme?

**Comment by abhisheks008** [comment]
Then make a fresh PR.

**Pull request closed without merging**
