### PR TITLE
Car Purchasing Prediction

### PR DESCRIPTION
**Pull request by Avik-creator**
# Pull Request for ML-Crate 💡

## Issue Title : Car Purchasing Prediction

- **Info about the related issue (Aim of the project)** :  Predict which are the cars to be purchased.
- **Name:** Avik Mukherjee
- **GitHub ID:** Avik-creator
- **Idenitfy yourself:** HSoC Participant.

Closes: #316

### CODE REVIEW

**Comment by Avik-creator** [comment]
@abhisheks008 Please check and review

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. The accuracy score of the best fitted model is not satisfactory, try to use better models and implement them. You have used only 3, there are lot of algos, try to implement them and check the best result.
2. In your README.md, under the Visualization, you have put the screenshots of the accuracy checking parameters. Visualization means, what you are visualizing from the dataset, not a model's accuracy parameters. Correct them.
3. Create a separate section in the README.md, named as Model Visualization, under this add your model's analysis.
4. In the conclusion, you have written the accuracy scores. You have not mentioned your EDA conclusions, add them. State which model is best and why, not just putting the accuracy scores. This looks really unprofessional.

@Avik-creator this is Level 3 issue, you have to be at the top of your mark.

**Comment by Avik-creator** [comment]
@abhisheks008 sorry for these mistakes

**Comment by abhisheks008** [comment]
Don't be sorry, you are learning new things, and I am guiding you to be the best version of you. Learn as much as you can.

@Avik-creator

**Comment by Avik-creator** [comment]
@abhisheks008 EDA means using Confusion Matrix to calculate our predictions?

**Comment by Avik-creator** [comment]
@abhisheks008 Please check it now.

**Review by abhisheks008 — APPROVED** [review]
Now compare your previous version of project with this, I guess you are getting my point why I have told you to do the changes. It looks pretty worthy now to be tagged as Level 3

@Avik-creator

**Comment by Avik-creator** [comment]
@abhisheks008 thanks for guiding

**Pull request merged**
