### PR TITLE
Cassava Leaf Disease Classification

### PR DESCRIPTION
**Pull request by CoderOMaster**
# Pull Request for ML-Crate 💡

## Issue Title:  

- **Info about the related issue (Aim of the project)** : 
- **Name:**  Keshav Arora
- **GitHub ID:**  CoderOMaster
- **Idenitfy yourself:**  JWOC Mentee

Closes: #issue number that will be closed through this PR 506

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please do the needful changes.

**Comment by CoderOMaster** [comment]
@abhisheks008 I hv already linked kaggle database in readme file though.Should I rename link.txt anyways?

**Comment by abhisheks008** [comment]
> @abhisheks008 I hv already linked kaggle database in readme file though.Should I rename link.txt anyways?

Yes

**Comment by CoderOMaster** [comment]
@abhisheks008 I have done all changes required.Please assign appropriate difficulty as per our previous discussion and approve the merge request.
Thank You

**Review by abhisheks008 — APPROVED** [review]
Approved.
@CoderOMaster

**Pull request merged**
