### PR TITLE
Narendra Modi - Text Speech Analysis

### PR DESCRIPTION
**Pull request by HarshRaj29004**
# Pull Request for ML-Crate 💡

## Issue Title: Narendra Modi - Text Speech Analysis

- **Info about the related issue (Aim of the project)** : This project is to analyze the speeches of Narendra Modi.
- **Name:** Harsh Raj
- **Email ID for further communication**: hr768381@gmail.com
- **GitHub ID:** https://github.com/HarshRaj29004
- **Idenitfy yourself:** SSOC'24 participant

Closes: #127 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change☑️

What sort of change have you made:
** Analyzed the speeches as per in the dataset and concluded few of the points from it.** 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by HarshRaj29004** [comment]
I renamed two image folders to rectify errors(just removed ':'). Changing of name does not affect any other files.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Use the README template and update the file. Here it is, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

**Comment by HarshRaj29004** [comment]
I have updated the Readme

**Review by abhisheks008 — APPROVED** [review]
Your PR is approved and ready to be merged.
@HarshRaj29004

**Pull request merged**
