### PR TITLE
Loan Repayment Prediction Project

### PR DESCRIPTION
**Pull request by aviralgarg05**
# Pull Request for ML-Crate 💡

## Issue Title:  Loan Repayment Prediction Project  #692  

- **Info about the related issue (Aim of the project)** :  Predict Repayment of Loan
- **Name:**  Aviral Garg
- **Email ID for further communication**:  gargaviral99@gmail.com
- **GitHub ID:**  aviralgarg05
- **Idenitfy yourself:**  SSOC Contributor

Closes: #issue number that will be closed through this PR 
#692 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
ML Algorithms to predict the repayment with greate accuracy
## Type of change ☑️
NA
What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested-  Tested using the previous data
Describe how have you verified the changes made-  Using other models based on credit score

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please follow the project structure and update the files.
@aviralgarg05

**Comment by aviralgarg05** [comment]
> Please follow the project structure and update the files. @aviralgarg05

What changes in the project structure?

**Comment by abhisheks008** [comment]
Project folder should be like this,
```
Loan Re-payment Prediction
|- Dataset
   |- dataset.csv
|- Images
   |- img1.png
   |- img2.png
   |- img3.png
   .  .
   .  .
   .  .
   |- img10.png
|- Model
   |- loan_repayment_prediction.ipynb
|- README.md
|- requirements.txt
```

**Comment by aviralgarg05** [comment]
Kindly check for all the required changes that are done.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
1. Create a folder as Images and put the all the project generated images inside that folder.
2. The name of the project folder should be same as the issue name.
3. Inside the README, it's better to create a table and put the all the accuracy checking parameters of the deployed models so that others can understand the logic of selecting the best fitted model among all the deployed models.

@aviralgarg05

**Review by abhisheks008 — APPROVED** [review]
Hi @aviralgarg05 looks good to me. Approved ✅

**Pull request merged**
