### PR TITLE
Aruco marker Detection

### PR DESCRIPTION
**Pull request by jayeshrdeotalu**
# Pull Request for ML-Crate 💡

## Issue Title: Aruco Marker Detection

- **Info about the related issue (Aim of the project)** : To detect and read Aruco markers from the images
- **Name:** Jayesh Deotalu
- **GitHub ID:**  jayeshrdeotalu
- **Idenitfy yourself:** Contributor

Closes: #551 number that will be closed through this PR

### Describe the add-ons or changes you've made 📃
I have collected images containing variety of aruco markers, using open cv's aruco marker library detected and read the markers within the images.

Give a clear description of what have you added or modifications made

Added  code with dataset to detect and read Aruco markers.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
code has be tested with images of multiple size with different types of aruco markers, multiple aruco libraries are used to make code more robust.

Describe how have you verified the changes made
Changes are verified through unit testing.

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Need to follow the project structure for this project. Update the project structure according to the requirement.

**Comment by jayeshrdeotalu** [comment]
Done...

**Comment by abhisheks008** [comment]
Hi @jayeshrdeotalu sorry for replying late. It will be better if you just put the URL of dataset inside a README.md in the Dataset folder instead of putting all the datapoints individually.

**Comment by jayeshrdeotalu** [comment]
Hello @abhisheks008 , the datapoints are collected from the google, so there is no specific source to the images.

**Comment by jayeshrdeotalu** [comment]
@abhisheks008 what happened...?

**Comment by abhisheks008** [comment]
Hi @jayeshrdeotalu this project repo will be participating SSOC. That's why removing all the pending tasks.

**Comment by jayeshrdeotalu** [comment]
Ohh @abhisheks008 could you please tell me how to apply for SSOC?

**Comment by abhisheks008** [comment]
Here's the link, https://ssocseason3.devfolio.co/

**Pull request closed without merging**
