### PR TITLE
Parameters of Cricket Analysis

### PR DESCRIPTION
**Pull request by SOMNATH0904**
# Pull Request for ML-Crate 💡

## Issue Title: Parameters of Cricket Analysis #723 

- **Info about the related issue (Aim of the project)** :  To perform Parameters of Cricket Analysis of "Indian Premier League"
- **Name:**  Somnath Shaw
- **Email ID for further communication**:  somnath.arcade3.2024@gmail.com
- **GitHub ID:**  https://github.com/SOMNATH0904
- **Idenitfy yourself:**  Student

Closes: #723 

### Describe the add-ons or changes you've made 📃
It is a comprehensive guide for conducting EDA on sports-related datasets. It aims to equip users with the skills necessary to uncover insights and patterns from raw data, leveraging various statistical and graphical techniques. This project covers a range of essential EDA steps, including data cleaning, data visualization, and summary statistics. Users will learn how to handle missing values, identify outliers, and understand the distribution and relationships within the data.

## Type of change ☑️
New Project added.

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️
The files are updated.
Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by SOMNATH0904** [comment]
@abhisheks008 Please Check this !!

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Hi @SOMNATH0904 please follow the project structure and update the project files accordingly.

**Comment by SOMNATH0904** [comment]
> Hi @SOMNATH0904 please follow the project structure and update the project files accordingly.

**@abhisheks008** I have updated the files according to the project structure. Can you please take a review ? ...

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Follow the README template and update the Model/README file, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

@SOMNATH0904

**Comment by SOMNATH0904** [comment]
@abhisheks008 Please check now!!

**Review by abhisheks008 — APPROVED** [review]
Looks good to me. Approved ✅ 
@SOMNATH0904

**Pull request merged**
